version: '3'

services:
  api-server:
    restart: always
    build: ./api-server
    expose:
      - "8001"
    volumes:
      - ./banken_config.json:/banken/banken_config.json
    command: /usr/local/bin/gunicorn -b 0.0.0.0:8001 app:app
    networks:
      - host
  
  dashboard:
    restart: always
    build: ./dashboard
    ports:
      - 8002:8002
    volumes:
      - ./banken_config.json:/banken/banken_config.json
    command: /usr/local/bin/gunicorn -b 0.0.0.0:8002 app:app
    networks:
      - host

networks:
  host: