version: '3'

services:
  api-server:
    restart: always
    build: ./api-server
    ports:
      - "8000:8000"
    volumes:
      - ./banken_config.json:/banken/banken_config.json
    command: /usr/local/bin/gunicorn -b 0.0.0.0:8000 app:app
    